### ISSUE TITLE
time_hour discrepancy with weather.rda 

### ISSUE THREAD

**Issue by dmcmurchy** [moderndive/pnwflights22#1]
I'm not sure if this is an issue with the original data source or in the version stored here, but the weather [data](https://github.com/moderndive/pnwflights22/blob/main/data/weather.rda) `time_hour` column appears to be using a UTC offset (+8 for the pacific time zone).

**Weather data**
|   year |   month |   hour | time_hour           |
|-------:|--------:|-------:|:--------------------|
|   2022 |       1 |      0 | 2022-01-01 08:00:00 |
|   2022 |       1 |      1 | 2022-01-01 09:00:00 |
|   2022 |       1 |      2 | 2022-01-01 10:00:00 |
|   2022 |       1 |      3 | 2022-01-01 11:00:00 |
|   2022 |       1 |      4 | 2022-01-01 12:00:00 |
|   2022 |       1 |      5 | 2022-01-01 13:00:00 |
|   2022 |       1 |      6 | 2022-01-01 14:00:00 |
|   2022 |       1 |      7 | 2022-01-01 15:00:00 |
|   2022 |       1 |      8 | 2022-01-01 16:00:00 |
|   2022 |       1 |      9 | 2022-01-01 17:00:00 |

Where the flights data is using local. 

**Flights data**
|   year |   month |   hour | time_hour           |
|-------:|--------:|-------:|:--------------------|
|   2022 |       1 |     23 | 2022-01-01 23:00:00 |
|   2022 |       1 |     22 | 2022-01-01 22:00:00 |
|   2022 |       1 |     23 | 2022-01-01 23:00:00 |
|   2022 |       1 |     23 | 2022-01-01 23:00:00 |
|   2022 |       1 |     23 | 2022-01-01 23:00:00 |
|   2022 |       1 |     23 | 2022-01-01 23:00:00 |
|   2022 |       1 |      0 | 2022-01-01 00:00:00 |
|   2022 |       1 |     22 | 2022-01-01 22:00:00 |
|   2022 |       1 |     23 | 2022-01-01 23:00:00 |
|   2022 |       1 |     23 | 2022-01-01 23:00:00 |

If you attempt to use the `time_hour` column to merge data between these two sources, you'd end up with some potentially misleading data. 

Based on what I could find on the Bureau of Transportation website all time values are local.

**Comment by ismayc** [comment]
Thanks for flagging! I'm investigating this further.

**Comment by ismayc** [comment]
@simonpcouch Could this have to do with how `time_hour` is created in the `get_weather_for_station()` function of {anyflights} [permalink](https://github.com/simonpcouch/anyflights/blob/407c758d37a48ba2780eb87a8505c4eabf24e06c/R/utils.R#L441C31-L441C42)? I was on Pacific time when I pulled this data down.

**Comment by ismayc** [comment]
@dmcmurchy After digging further into this, it does seem that a `tz` argument is missing when the `anyflights` package that I used when it pulls down the weather data. For example, I'm currently on Mountain time which appears to be showing my values as an hour off where it should be (see below). I've created a PR into {anyflights} with what I think is a fix for this [here](https://github.com/simonpcouch/anyflights/pull/25).

<img width="1126" alt="Screenshot 2024-12-26 at 2 11 32 PM" src="https://github.com/user-attachments/assets/366254e5-1ff7-499c-8f13-7f7e47780a80" />

**Comment by ismayc** [comment]
Please reopen and tag me if you see the same issue again. Apologies for the very long delay!

**Comment by dmcmurchy** [comment]
I had forgotten I submitted this issue, glad it wasn't something I was doing on my end.  I had to go back and see what I was doing with this data and it was while I was recreating the CSV data used in the [Analyzing Flight Delays and Cancellations](https://app.datacamp.com/learn/projects/1962) project on DataCamp. I used the [pyreadr](https://github.com/ofajardo/pyreadr) python package and .rda files on your github to do so.  

Do you know if you'll be updating the related data files you have on Github? If not, I'll just put a note into the related notebook. 

Thanks

**Comment by ismayc** [comment]
Ah, good deal! I'll plan to update the data whenever I get a response on my anyflights request. I can reach out to DataCamp on getting things updated there too if needed.
